/**
 * Real output of the configuration generators for the reference topology (Checkmk on dokploy, relay01 over
 * WireGuard). Regenerate rather than edit by hand. Secrets are placeholders, exactly as the product writes them.
 */
export const generatedFiles = [
  {
    path: "dokploy/wireguard/wg0.conf",
    label: "WireGuard",
    source: "wg-platform \u00b7 dokploy",
    content:
      "# Generated by Nivrox Topology Manager. Change the topology, not this file.\n# WireGuard network 'wg-platform' (wg-platform) on dokploy.\n# Contains no secrets: keys and passwords are injected from the credential store at deployment.\n[Interface]\nAddress = 10.50.0.1/24\nListenPort = 51820\nPrivateKey = <injected: wireguard/wg-platform/dokploy/private-key>\n\n[Peer]\n# relay01 (relay01)\nPublicKey = <injected: wireguard/wg-platform/relay01/public-key>\nAllowedIPs = 10.50.0.2/32\n",
  },
  {
    path: "dokploy/compose/monitoring/compose.yaml",
    label: "Docker Compose",
    source: "monitoring \u00b7 dokploy",
    content:
      '# Generated by Nivrox Topology Manager. Change the topology, not this file.\n# Compose project for \'monitoring\' (monitoring) on dokploy.\n# Contains no secrets: keys and passwords are injected from the credential store at deployment.\nname: "monitoring"\n\nservices:\n  checkmk:\n    image: "checkmk/check-mk-raw:2.4.0-latest"\n    restart: unless-stopped\n    environment:\n      CMK_SITE_ID: "monitoring"\n    ports:\n      - "10.50.0.1:8000:8000/tcp"  # agent-receiver\n    volumes:\n      - "checkmk-sites:/omd/sites"\n    tmpfs:\n      - "/opt/omd/sites/monitoring/tmp:uid=1000,gid=1000"\n\nvolumes:\n  checkmk-sites: {}\n',
  },
  {
    path: "dokploy/firewall/nivrox.nft",
    label: "nftables",
    source: "fw-dokploy \u00b7 dokploy",
    content:
      '#!/usr/sbin/nft -f\n# Generated by Nivrox Topology Manager. Change the topology, not this file.\n# Firewall \'dokploy firewall\' (fw-dokploy) on dokploy.\n# Additive: managed rules live in table \'inet nivrox\'; other tables are left untouched.\n# Re-applying replaces only this table (declare, delete, recreate).\ntable inet nivrox\ndelete table inet nivrox\n\ntable inet nivrox {\n  chain input {\n    type filter hook input priority filter; policy drop;\n    ct state established,related accept\n    ct state invalid drop\n    iifname "lo" accept\n    ip saddr 198.51.100.0/24 meta l4proto tcp th dport 22 accept comment "rule 1: SSH from management"\n    meta l4proto udp th dport 51820 accept comment "rule 2: WireGuard"\n    ip saddr 10.50.0.0/24 meta l4proto tcp th dport 8000 accept comment "rule 3: Checkmk Agent Receiver over WireGuard"\n  }\n\n  # Docker-published ports are DNATed before INPUT; filter them on the forward path\n  # by their original (pre-NAT) destination port.\n  chain forward {\n    type filter hook forward priority filter; policy accept;\n    ct state established,related accept\n    ct status dnat jump published\n  }\n\n  chain published {\n    ip saddr 198.51.100.0/24 meta l4proto tcp ct original proto-dst 22 accept comment "rule 1: SSH from management"\n    meta l4proto udp ct original proto-dst 51820 accept comment "rule 2: WireGuard"\n    ip saddr 10.50.0.0/24 meta l4proto tcp ct original proto-dst 8000 accept comment "rule 3: Checkmk Agent Receiver over WireGuard"\n    drop\n  }\n}\n',
  },
  {
    path: "relay01/checkmk/register-agent.sh",
    label: "Checkmk agent",
    source: "relay01 \u2192 checkmk",
    content:
      "#!/bin/sh\n# Generated by Nivrox Topology Manager. Change the topology, not this file.\n# Registers the Checkmk agent on relay01 with site 'monitoring' via the Agent Receiver.\n# Simulation: TCP 8000 to 10.50.0.1 is reachable.\n# Requires the Checkmk agent package (cmk-agent-ctl) on this host.\n# Contains no secrets: keys and passwords are injected from the credential store at deployment.\nset -eu\n: \"${CMK_AUTOMATION_SECRET:?must be provided by the deployment engine}\"\ncmk-agent-ctl register \\\n  --hostname 'relay01.example.internal' \\\n  --server 'checkmk.example.internal:8000' \\\n  --site 'monitoring' \\\n  --user 'automation' \\\n  --password \"$CMK_AUTOMATION_SECRET\" \\\n  --trust-cert\n",
  },
] as const;
